import json
import os
import urllib.parse
from datetime import datetime

def generate_reports(data, formats, folder_path):
    """
    Genera i report nei formati richiesti con codifica UTF-8 per Safari e QuickLook.
    """
    target_clean = data["target"].replace(".", "_")
    timestamp_slug = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_name = f"Security_Audit_{target_clean}_{timestamp_slug}"
    
    generated_files = []

    if "json" in formats:
        path = os.path.join(folder_path, f"{base_name}.json")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4, ensure_ascii=False)
        generated_files.append(path)

    if "txt" in formats:
        path = os.path.join(folder_path, f"{base_name}.txt")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_generate_txt_content(data))
        generated_files.append(path)

    if "html" in formats:
        path = os.path.join(folder_path, f"{base_name}.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(_generate_html_content(data))
        generated_files.append(path)

    return generated_files

def _linkify(target, path=""):
    """Crea un link HTML sicuro partendo dal target e dal path."""
    if not target: return ""
    base = target if "://" in target else f"https://{target}"
    url = urllib.parse.urljoin(base, path)
    # Rimuoviamo eventuali backslash indesiderati per i link web
    url = url.replace("\\", "/")
    return f'<a href="{url}" target="_blank" class="link-node">{path if path else target}</a>'

def _generate_txt_content(data):
    lines = [
        "="*60,
        "          🛡️ SECURITY AUDIT REPORT - PROFESSIONAL EDITION",
        "="*60,
        f"TARGET    : {data['target']}",
        f"TIMESTAMP : {data['timestamp']}",
        "-"*60,
    ]
    
    if data.get("waf_alert"):
        lines.append("\n[!!!] INTEGRITY ALERT: WAF DECEPTION DETECTED")
        lines.append("Target firewall attempted to spoof results. Findings might be filtered.")

    lines.append("\n[1] NETWORK SCAN")
    for s in data["scans"]:
        v_tag = "VERIFIED" if s.get("verified") else "STEALTH"
        lines.append(f"- Port {s['port']} [{v_tag}]: {s['service']}")
    
    if data.get("ssl"):
        s = data["ssl"]
        lines.append(f"\n[2] SSL/TLS CERTIFICATE")
        lines.append(f"  Hostname : {s['hostname']}")
        lines.append(f"  Issuer   : {s['issuer']}")
        lines.append(f"  Expiry   : {s['expiry']} ({s['days_left']} days left)")

    lines.append("\n[3] WEB RECON")
    lines.append(f"Hardening Score: {data['recon']['score']}/6")
    for h in data["recon"]["headers"]:
        lines.append(f"  {h}")
    
    if data.get("http_methods"):
        lines.append("\n[4] HTTP VERBS AUDIT")
        for v in data["http_methods"]:
            lines.append(f"  {v}")
            
    if data["directories"]:
        lines.append("\n[5] DIRECTORIES FOUND")
        for d in data["directories"]:
            lines.append(f"  📂 {d}")
            
    lines.append("\n" + "="*60)
    lines.append("Generated by Security Toolkit Pro v5.6")
    return "\n".join(lines)

def _generate_html_content(data):
    target_host = data["target"]
    css = """
    :root { --bg: #0B0F1A; --card: #161B22; --accent: #58A6FF; --text: #C9D1D9; --gray: #8B949E; --red: #F85149; --green: #3FB950; --yellow: #D29922; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background-color: var(--bg); color: var(--text); margin: 0; padding: 20px; line-height: 1.5; }
    .container { max-width: 1200px; margin: auto; }
    
    .header { background: var(--card); padding: 30px; border-radius: 12px; border-left: 6px solid var(--accent); margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; }
    .meta-box { font-size: 14px; color: var(--gray); }
    .score-badge { background: rgba(88, 166, 255, 0.1); color: var(--accent); padding: 10px 20px; border-radius: 50px; font-weight: bold; border: 1px solid var(--accent); }

    .grid-audit { display: grid; grid-template-columns: 1.2fr 0.8fr; gap: 20px; }
    @media (max-width: 900px) { .grid-audit { grid-template-columns: 1fr; } }

    .card { background: var(--card); padding: 25px; border-radius: 12px; border: 1px solid #30363D; margin-bottom: 20px; height: fit-content; }
    h2 { color: var(--accent); font-size: 18px; margin-top: 0; border-bottom: 1px solid #30363D; padding-bottom: 10px; margin-bottom: 20px; text-transform: uppercase; }
    
    .waf-banner { background: rgba(248, 81, 73, 0.1); border: 1px solid var(--red); color: var(--red); padding: 15px; border-radius: 8px; margin-bottom: 20px; font-weight: bold; text-align: center; }
    
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th { text-align: left; padding: 12px; color: var(--gray); border-bottom: 2px solid #30363D; font-size: 11px; text-transform: uppercase; }
    td { padding: 12px; border-bottom: 1px solid #21262D; }

    .tag { padding: 3px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; text-transform: uppercase; }
    .tag-red { background: rgba(248, 81, 73, 0.2); color: var(--red); border: 1px solid var(--red); }
    .tag-green { background: rgba(63, 185, 80, 0.2); color: var(--green); border: 1px solid var(--green); }
    .tag-yellow { background: rgba(210, 153, 34, 0.2); color: var(--yellow); border: 1px solid var(--yellow); }

    .link-node { color: var(--accent); text-decoration: none; transition: 0.2s; font-weight: 500; }
    .link-node:hover { text-decoration: underline; opacity: 0.8; }

    ul { list-style: none; padding: 0; margin: 0; }
    li { background: #0D1117; margin: 8px 0; padding: 12px; border-radius: 8px; font-size: 13px; display: flex; align-items: center; border-left: 2px solid var(--accent); }
    
    .footer { text-align: center; color: var(--gray); margin-top: 40px; font-size: 11px; padding: 20px; border-top: 1px solid #30363D; }
    """

    waf_banner = ""
    if data.get("waf_alert"):
        waf_banner = f'<div class="waf-banner">⚠️ WAF INTEGRITY ALERT: Target is attempting to spoof results (Deception Detected)</div>'

    # --- NETWORK COLUMN ---
    net_rows = ""
    for s in data["scans"]:
        is_v = s.get("verified", False)
        v_tag = "VERIFIED" if is_v else "STEALTH"
        tag_class = "tag-green" if is_v else "tag-yellow"
        net_rows += f"<tr><td><strong>{s['port']}</strong></td><td><span class='tag {tag_class}'>{v_tag}</span></td><td>{s['service']}</td></tr>"

    # --- SSL SECTION ---
    ssl_html = ""
    if data.get("ssl") and data["ssl"].get("status") == "success":
        s = data["ssl"]
        sans_links = [f'<span style="margin-right:8px;">{_linkify(sub)}</span>' for sub in s['sans']]
        ssl_html = f"""
        <div class="card">
            <h2>🔒 SSL/TLS Audit</h2>
            <div style="font-size:13px; line-height:1.8;">
                <div><span style="color:var(--gray)">HOSTNAME:</span> {_linkify(s['hostname'])}</div>
                <div><span style="color:var(--gray)">ISSUER:</span> {s['issuer']}</div>
                <div><span style="color:var(--gray)">EXPIRES:</span> {s['expiry']} ({s['days_left']}d)</div>
                <div><span style="color:var(--gray)">PROTOCOL:</span> {s['protocol']}</div>
            </div>
            <h4 style="color:var(--gray); font-size:11px; margin-top:15px; border-top:1px solid #30363D; padding-top:10px;">SUBJECT ALTERNATIVE NAMES</h4>
            <div style="display:flex; flex-wrap:wrap; margin-top:5px;">{" ".join(sans_links)}</div>
        </div>
        """

    # --- RECON COLUMN ---
    recon_html = f"""
    <div class="card">
        <h2>🕵️ Web Hardening Analysis</h2>
        <ul>{" ".join([f"<li>{h}</li>" for h in data["recon"]["headers"]])}</ul>
    </div>
    """

    # --- VERBS AUDIT ---
    verbs_html = ""
    if data.get("http_methods"):
        v_rows = ""
        for v in data["http_methods"]:
            tag = "tag-green" if "✅" in v else ("tag-red" if "❌" in v else "tag-yellow")
            v_msg = v.replace("✅ ", "").replace("❌ ", "").replace("ℹ️ ", "").replace("⚠️ ", "")
            v_rows += f"<tr><td><span class='tag {tag}'>AUDIT</span></td><td>{v_msg}</td></tr>"
        verbs_html = f'<div class="card"><h2>💉 HTTP Method Policy</h2><table>{v_rows}</table></div>'

    # --- DISCOVERY ---
    discovery_html = ""
    if data.get("directories") or data["recon"].get("robots"):
        items = []
        if data.get("directories"):
            items += [f"<li>📂 {_linkify(target_host, d)}</li>" for d in data["directories"]]
        if data["recon"].get("robots"):
            items += [f"<li>🤖 Robots: {_linkify(target_host, r)}</li>" for r in data["recon"]["robots"]]
        
        if items:
            discovery_html = f'<div class="card"><h2>🔍 Resource Discovery</h2><ul>{" ".join(items)}</ul></div>'

    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Audit Dashboard - {target_host}</title>
        <style>{css}</style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <div>
                    <h1>🛡️ Enterprise Security Audit</h1>
                    <div class="meta-box">Target: {target_host} | Scanned: {data['timestamp']}</div>
                </div>
                <div class="score-badge">SCORE: {data['recon']['score']}/6</div>
            </div>

            {waf_banner}

            <div class="grid-audit">
                <div class="col-left">
                    <div class="card">
                        <h2>🌐 Network Scan</h2>
                        <table>
                            <thead><tr><th>Port</th><th>Status</th><th>Service</th></tr></thead>
                            <tbody>{net_rows}</tbody>
                        </table>
                    </div>
                    {recon_html}
                </div>
                
                <div class="col-right">
                    {ssl_html}
                    {verbs_html}
                    {discovery_html}
                </div>
            </div>

            <div class="footer">
                <strong>ST PRO v5.6 - 100% Audit Integrity Certified</strong><br>
                Generated via Professional Security Suite &copy; {datetime.now().year}
            </div>
        </div>
    </body>
    </html>
    """
    return html